version: "3.8"

services:
  neo4j:
    image: neo4j:2025.06.2
    container_name: neo4j-bread
    restart: always
    ports:
      - "7474:7474"   # Web UI
      - "7687:7687"   # Bolt protocol, used for Python driver, etc.
    environment:
      NEO4J_AUTH: "neo4j/triforce"  # ← Replace with your desired password
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-bread
    restart: always
    ports:
      - "5672:5672"   # RabbitMQ communication (AMQP protocol)
      - "15672:15672" # Management interface (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: haowei
      RABBITMQ_DEFAULT_PASS: bread861122 

  redis:
    image: redis:7
    container_name: redis-bread
    restart: always
    ports:
      - "6379:6379"   # Redis port
    volumes:
      - redis_data:/data
    restart: always
    command: ["redis-server", "--requirepass", "bread861122"] 
    ports:
      - "6379:6379"   # Redis protocol
    volumes:
      - redis_data:/data

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  redis_data:
