services:
  mongodb:
    image: mongo:7.0.22-jammy
    container_name: mongo-bread
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: haowei
      MONGO_INITDB_ROOT_PASSWORD: bread861122
    volumes:
      - mongo-data:/data/db
    networks:
      - longshot-net

  mongo-express: # MongoDB web-based admin interface
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_ENABLED: "true"
      ME_CONFIG_MONGODB_URL: "mongodb://haowei:bread861122@mongo-bread:27017"
    networks:
      - longshot-net
    restart: unless-stopped

  # warehouse:
  #   build:
  #     context: ./warehouse
  #     dockerfile: dockerfile
  #   container_name: warehouse-bread
  #   restart: unless-stopped
  #   ports:
  #     - "8000:8000"   # Warehouse API port
  #   environment:
  #     - PYTHONPATH=/app
  #   depends_on:
  #     - mongodb
  #     - neo4j
  #     - redis
  #     - rabbitmq
  #   networks:
  #     - longshot-net
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 40s

volumes:
  mongo-data:

networks:
  longshot-net:
    external: true
    name: longshot-net
    driver: bridge
